//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.15 at 11:43:19 AM EST
//

package io.github.spannm.jackcess.encrypt.model.cert;

/**
 * Java class for CT_CertificateKeyEncryptor complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>
 * &lt;complexType name="CT_CertificateKeyEncryptor"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="encryptedKeyValue" use="required" type="{http://www.w3.org/2001/XMLSchema}base64Binary" /&gt;
 *       &lt;attribute name="X509Certificate" use="required" type="{http://www.w3.org/2001/XMLSchema}base64Binary" /&gt;
 *       &lt;attribute name="certVerifier" use="required" type="{http://www.w3.org/2001/XMLSchema}base64Binary" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 */
// @XmlAccessorType(XmlAccessType.FIELD)
// @XmlType(name = "CT_CertificateKeyEncryptor")
@SuppressWarnings("PMD.VisibilityModifier")
public class CTCertificateKeyEncryptor {

    // @XmlAttribute(required = true)
    protected byte[] encryptedKeyValue;
    // @XmlAttribute(name = "X509Certificate", required = true)
    protected byte[] x509Certificate;
    // @XmlAttribute(required = true)
    protected byte[] certVerifier;

    /**
     * Gets the value of the encryptedKeyValue property.
     *
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getEncryptedKeyValue() {
        return encryptedKeyValue;
    }

    /**
     * Sets the value of the encryptedKeyValue property.
     *
     * @param _value
     *     allowed object is
     *     byte[]
     */
    public void setEncryptedKeyValue(byte[] _value) {
        this.encryptedKeyValue = _value;
    }

    /**
     * Gets the value of the x509Certificate property.
     *
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getX509Certificate() {
        return x509Certificate;
    }

    /**
     * Sets the value of the x509Certificate property.
     *
     * @param _value
     *     allowed object is
     *     byte[]
     */
    public void setX509Certificate(byte[] _value) {
        this.x509Certificate = _value;
    }

    /**
     * Gets the value of the certVerifier property.
     *
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCertVerifier() {
        return certVerifier;
    }

    /**
     * Sets the value of the certVerifier property.
     *
     * @param _value
     *     allowed object is
     *     byte[]
     */
    public void setCertVerifier(byte[] _value) {
        this.certVerifier = _value;
    }

}
