//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.15 at 11:43:19 AM EST
//

package io.github.spannm.jackcess.encrypt.model.cert;

/**
 * Java class for ST_CertificateKeyEncryptorUri.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>
 * &lt;simpleType name="ST_CertificateKeyEncryptorUri"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="http://schemas.microsoft.com/office/2006/keyEncryptor/certificate"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
// @XmlType(name = "ST_CertificateKeyEncryptorUri")
// @XmlEnum
public enum STCertificateKeyEncryptorUri {

    // @XmlEnumValue("http://schemas.microsoft.com/office/2006/keyEncryptor/certificate")
    HTTP_SCHEMAS_MICROSOFT_COM_OFFICE_2006_KEY_ENCRYPTOR_CERTIFICATE("http://schemas.microsoft.com/office/2006/keyEncryptor/certificate");

    private final String value;

    STCertificateKeyEncryptorUri(String _v) {
        value = _v;
    }

    public String value() {
        return value;
    }

    public static STCertificateKeyEncryptorUri fromValue(String _v) {
        for (STCertificateKeyEncryptorUri c : values()) {
            if (c.value.equals(_v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(_v);
    }

}
