name: Build with JDK 17 on Ubuntu

on:
    push:
        branches:
        - master
    pull_request:
        branches:
        - master
    workflow_dispatch:
        branches:
        - master

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4

        -   name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven

        -   name: Build with Maven/JDK 17 on Ubuntu
            run: mvn --batch-mode --file pom.xml clean verify
