//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.15 at 11:43:19 AM EST
//

package io.github.spannm.jackcess.encrypt.model;

/**
 * Java class for CT_DataIntegrity complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>
 * &lt;complexType name="CT_DataIntegrity"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="encryptedHmacKey" use="required" type="{http://www.w3.org/2001/XMLSchema}base64Binary" /&gt;
 *       &lt;attribute name="encryptedHmacValue" use="required" type="{http://www.w3.org/2001/XMLSchema}base64Binary" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
// @XmlAccessorType(XmlAccessType.FIELD)
// @XmlType(name = "CT_DataIntegrity")
@SuppressWarnings("PMD.VisibilityModifier")
public class CTDataIntegrity {

    // @XmlAttribute(required = true)
    protected byte[] encryptedHmacKey;
    // @XmlAttribute(required = true)
    protected byte[] encryptedHmacValue;

    /**
     * Gets the value of the encryptedHmacKey property.
     *
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getEncryptedHmacKey() {
        return encryptedHmacKey;
    }

    /**
     * Sets the value of the encryptedHmacKey property.
     *
     * @param _value
     *     allowed object is
     *     byte[]
     */
    public void setEncryptedHmacKey(byte[] _value) {
        this.encryptedHmacKey = _value;
    }

    /**
     * Gets the value of the encryptedHmacValue property.
     *
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getEncryptedHmacValue() {
        return encryptedHmacValue;
    }

    /**
     * Sets the value of the encryptedHmacValue property.
     *
     * @param _value allowed object is byte[]
     */
    public void setEncryptedHmacValue(byte[] _value) {
        this.encryptedHmacValue = _value;
    }

}
