//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.15 at 11:43:19 AM EST
//

package io.github.spannm.jackcess.encrypt.model;

/**
 * Java class for CT_Encryption complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>
 * &lt;complexType name="CT_Encryption"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="keyData" type="{http://schemas.microsoft.com/office/2006/encryption}CT_KeyData"/&gt;
 *         &lt;element name="dataIntegrity" type="{http://schemas.microsoft.com/office/2006/encryption}CT_DataIntegrity" minOccurs="0"/&gt;
 *         &lt;element name="keyEncryptors" type="{http://schemas.microsoft.com/office/2006/encryption}CT_KeyEncryptors"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
// @XmlAccessorType(XmlAccessType.FIELD)
// @XmlType(name = "CT_Encryption", propOrder = {
// "keyData",
// "dataIntegrity",
// "keyEncryptors"
// })
@SuppressWarnings("PMD.VisibilityModifier")
public class CTEncryption {

    // @XmlElement(required = true)
    protected CTKeyData       keyData;
    protected CTDataIntegrity dataIntegrity;
    // @XmlElement(required = true)
    protected CTKeyEncryptors keyEncryptors;

    /**
     * Gets the value of the keyData property.
     *
     * @return
     *     possible object is
     *     {@link CTKeyData }
     *
     */
    public CTKeyData getKeyData() {
        return keyData;
    }

    /**
     * Sets the value of the keyData property.
     *
     * @param value
     *     allowed object is
     *     {@link CTKeyData }
     *
     */
    public void setKeyData(CTKeyData value) {
        this.keyData = value;
    }

    /**
     * Gets the value of the dataIntegrity property.
     *
     * @return
     *     possible object is
     *     {@link CTDataIntegrity }
     *
     */
    public CTDataIntegrity getDataIntegrity() {
        return dataIntegrity;
    }

    /**
     * Sets the value of the dataIntegrity property.
     *
     * @param value
     *     allowed object is
     *     {@link CTDataIntegrity }
     *
     */
    public void setDataIntegrity(CTDataIntegrity value) {
        this.dataIntegrity = value;
    }

    /**
     * Gets the value of the keyEncryptors property.
     *
     * @return
     *     possible object is
     *     {@link CTKeyEncryptors }
     *
     */
    public CTKeyEncryptors getKeyEncryptors() {
        return keyEncryptors;
    }

    /**
     * Sets the value of the keyEncryptors property.
     *
     * @param value
     *     allowed object is
     *     {@link CTKeyEncryptors }
     *
     */
    public void setKeyEncryptors(CTKeyEncryptors value) {
        this.keyEncryptors = value;
    }

}
