//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.15 at 11:43:19 AM EST
//

package io.github.spannm.jackcess.encrypt.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Java class for CT_KeyEncryptors complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>
 * &lt;complexType name="CT_KeyEncryptors"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="keyEncryptor" type="{http://schemas.microsoft.com/office/2006/encryption}CT_KeyEncryptor" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
// @XmlAccessorType(XmlAccessType.FIELD)
// @XmlType(name = "CT_KeyEncryptors", propOrder = {
// "keyEncryptor"
// })
@SuppressWarnings("PMD.VisibilityModifier")
public class CTKeyEncryptors {

    // @XmlElement(required = true)
    protected List<CTKeyEncryptor> keyEncryptor;

    /**
     * Gets the value of the keyEncryptor property.
     *
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyEncryptor property.</p>
     *
     * <p>For example, to add a new item, do as follows:</p>
     *
     * <pre>
     *    getKeyEncryptor().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link CTKeyEncryptor}.</p>
     *
     */
    public List<CTKeyEncryptor> getKeyEncryptor() {
        if (keyEncryptor == null) {
            keyEncryptor = new ArrayList<>();
        }
        return this.keyEncryptor;
    }

}
