//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.01.15 at 11:43:19 AM EST
//

package io.github.spannm.jackcess.encrypt.model.password;

/**
 * Java class for ST_PasswordKeyEncryptorUri.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>
 * &lt;simpleType name="ST_PasswordKeyEncryptorUri"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="http://schemas.microsoft.com/office/2006/keyEncryptor/password"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
// @XmlType(name = "ST_PasswordKeyEncryptorUri", namespace = "http://schemas.microsoft.com/office/2006/keyEncryptor/password")
// @XmlEnum
public enum STPasswordKeyEncryptorUri {

    // @XmlEnumValue("http://schemas.microsoft.com/office/2006/keyEncryptor/password")
    HTTP_SCHEMAS_MICROSOFT_COM_OFFICE_2006_KEY_ENCRYPTOR_PASSWORD(
        "http://schemas.microsoft.com/office/2006/keyEncryptor/password");

    private final String value;

    STPasswordKeyEncryptorUri(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static STPasswordKeyEncryptorUri fromValue(String v) {
        for (STPasswordKeyEncryptorUri c : values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
